# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33d9b177e72be1ad2f16aaa128af0ac993b6f17239ccd061fbc49c185b175c1a2333b1e44fff11edf6a6e0e36b8db993973acff00dcb5db4a44d074dae9561f1

test:
  secret_key_base: a47adf0d6d2fc9683781a8b88520b5fa3b3eda142c5dfa3b4c431cf55a382a1b77dc2dc49842809d2b9cb1fec33d7b65cb0dc6654c630a5938667377aca2bb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
